# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build firmware and deploy GitHub Page

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      #Build CYD
      - name: Build CYD
        run: platformio run -e cyd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CYD Firmware
          path: .pio/build/cyd/firmware.bin
          if-no-files-found: error
      - name: Copy compiled binaries for webflash
        run: |
          mkdir GitHubPages/ESPWebTools/cyd

          # Copy the manifest file for the CYD
          cp GitHubPages/ESPWebTools/manifest.json GitHubPages/ESPWebTools/cyd

          cp .pio/build/cyd/bootloader.bin GitHubPages/ESPWebTools/cyd
          cp .pio/build/cyd/partitions.bin GitHubPages/ESPWebTools/cyd
          cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin GitHubPages/ESPWebTools/cyd
          cp .pio/build/cyd/firmware.bin GitHubPages/ESPWebTools/cyd

      #Build cyd2usb
      - name: Build cyd2usb
        run: platformio run -e cyd2usb
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cyd2usb Firmware
          path: .pio/build/cyd2usb/firmware.bin
          if-no-files-found: error
      - name: Copy compiled binaries for webflash
        run: |
          mkdir GitHubPages/ESPWebTools/cyd2usb

          # Copy the manifest file for the cyd2usb
          cp GitHubPages/ESPWebTools/manifest.json GitHubPages/ESPWebTools/cyd2usb

          cp .pio/build/cyd2usb/bootloader.bin GitHubPages/ESPWebTools/cyd2usb
          cp .pio/build/cyd2usb/partitions.bin GitHubPages/ESPWebTools/cyd2usb
          cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin GitHubPages/ESPWebTools/cyd2usb
          cp .pio/build/cyd2usb/firmware.bin GitHubPages/ESPWebTools/cyd2usb

      #Build Matrix
      - name: Build Matrix
        run: platformio run -e trinity
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CYD Firmware
          path: .pio/build/trinity/firmware.bin
          if-no-files-found: error
      - name: Copy compiled binaries for webflash
        run: |
          mkdir GitHubPages/ESPWebTools/matrix

          # Copy the manifest file for the CYD
          cp GitHubPages/ESPWebTools/manifest.json GitHubPages/ESPWebTools/matrix

          cp .pio/build/trinity/bootloader.bin GitHubPages/ESPWebTools/matrix
          cp .pio/build/trinity/partitions.bin GitHubPages/ESPWebTools/matrix
          cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin GitHubPages/ESPWebTools/matrix
          cp .pio/build/trinity/firmware.bin GitHubPages/ESPWebTools/matrix

      # Build GitHub Page
      - name: Setup Github Page
        uses: actions/configure-pages@v3

      - name: Build GitHub Page with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./GitHubPages
          destination: ./_site

      - name: Upload GitHub Page Artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
